---
- name: installation of dependencies
  tags: dependencies, centos
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - make
      - gettext
      - automake
      - autoconf
      - wget
      - openssl-devel
      - net-snmp
      - net-snmp-utils
      - python
      - python2-pip
      - python3-pip
    state: latest

- name: creating path directory
  file:
    path: ~/prometheus
    state: directory

- name: installation of  prometheus
  unarchive:
    src: /home/jhoana/Downloads/prometheus-2.47.2.linux-amd64.tar.gz
    dest: ~/prometheus
    mode: 0777
    owner: root
    group: root

- name: creating prometheus user
  user:
    name: prometheus
    system: yes

- name: start and enable prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
