---
- name: installation of dependencies
  tags: dependencies, centos
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - make
      - gettext
      - automake
      - autoconf
      - wget
      - openssl-devel
      - net-snmp
      - net-snmp-utils
      - python
      - python2-pip
      - python3-pip
    state: latest

- name: creating path directory
  file:
    path: ~/prometheus
    state: directory

- name: downloading and installation of  prometheus
  unarchive:
    src: /home/jhoana/Downloads/prometheus-2.47.2.linux-amd64.tar.gz
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root

- name: creating prometheus user
  user:
    name: prometheus
    system: yes

- name: creating prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: copying prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus
    owner: prometheus
    group: prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
