---
- name: installation of dependencies
  tags: dependencies, ubuntu
  apt:
    name:
      - gcc
      - perl
      - wget
      - curl
    state: latest

- name: creating path directory
  file:
    path: ~/prometheus
    state: directory

- name: installation of  prometheus
  unarchive:
    src: /home/jhoana/Downloads/prometheus-2.47.2.linux-amd64.tar.gz
    dest: ~/prometheus
    mode: 0755
    owner: root
    group: root

- name: creating prometheus user
  user:
    name: prometheus
    system: yes

- name: creating prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: true
